### ISSUE TITLE
Rotas no CakePHP 3

### ISSUE THREAD

**Issue by tgbaldo** [CakePHPBrasil/blog#10]
Meus nobres, antes de mais nada, quero dizer que já resolvi o problema, porém, preciso saber se não tem um caminho mais prático pra isso.

Tenho um controller chamado users com minhas actions funcionando bonitinho, mas preciso deixar a URL em formato português mesmo: /usuarios.

No Laravel eu resolvo isso em UMA linha:

`Route::resource('usuarios', 'UsersController');`

Porém no Cake3 eu preciso fazer isso:

```
Router::scope('/usuarios', function (RouteBuilder $routes) {

    $routes->connect('/', ['controller' => 'users'] );
    $routes->connect('/:action', ['controller' => 'users']);
    $routes->connect('/:action/*', ['controller' => 'users']);

    $routes->fallbacks(DashedRoute::class);
});
```
Não tem como fugir disso?

Abs!

**Comment by erikfig** [comment]
Veja se ajuda:

http://book.cakephp.org/3.0/en/development/routing.html#creating-restful-routes

**Comment by tgbaldo** [comment]
@erikfig, deixei assim e não deu certo meu velho:

```
Router::scope('/usuarios', function (RouteBuilder $routes) {
    $routes->resources('Users');
     $routes->fallbacks(DashedRoute::class);
});
```

**Comment by maiconpinto** [comment]
oi @tgbaldo eu não sei se resolve teu caso, mas testei aqui e funcionou para traduzir o controller, pelo menos:

```php
$routes->connect('/artigos', ['controller' => 'Articles']);
$routes->connect('/artigos/:action', ['controller' => 'Articles']);
```
