### ISSUE TITLE
Preparar um tema melhor

### ISSUE THREAD

**Issue by erikfig** [CakePHPBrasil/blog#2]
O tema atual do blog é o padrão do Jekyll e é bem simples, então precisamos melhorar isso ai.

O nome do tema atual é o Minimal: [https://github.com/henrythemes/jekyll-minimal-theme](https://github.com/henrythemes/jekyll-minimal-theme).

Para alterar basta replicar os diretórios **_layout** e **css** dentro do nosso projeto e proceder com as alterações necessárias.

Aqui a documentação o Jekyll sobre o assunto: [https://jekyllrb.com/docs/themes/#overriding-theme-defaults](https://jekyllrb.com/docs/themes/#overriding-theme-defaults)

**Comment by maiconpinto** [comment]
Oi estava vendo uns themes para Jekyll, e encontrei estas sugestões:
Type Theme ([source](https://github.com/rohanchandra/type-theme), [demo](https://rohanchandra.github.io/type-theme/))
Clean Blog ([source](https://github.com/BlackrockDigital/startbootstrap-clean-blog-jekyll),[demo](http://blackrockdigital.github.io/startbootstrap-clean-blog-jekyll/))
Beutiful jekyll ([source](https://github.com/daattali/beautiful-jekyll), [demo](http://deanattali.com/beautiful-jekyll/))

Bom fica a sugestão, se precisarem de ajuda para implementar, posso ajudar.

**Comment by erikfig** [comment]
Eu gostei do Type Theme, com outra cor claro, os outros também são legais, mas o meu preferido foi o Type Theme.

Att. Erik Figueiredo

**Comment by maiconpinto** [comment]
Oi @erikfig o @flavianohonorato encontrou um outro template. Acho que ele ficou responsável por atualizar o layout do site.

**Comment by flavianohonorato** [comment]
Já o comuniquei, ele inclusive já autorizou, devo estar subindo as alterações esse final de semana.
