### ISSUE TITLE
O link do slack no readme está quebrado

### ISSUE THREAD

**Issue by recoverjp** [CakePHPBrasil/blog#22]
Coloca o link direto do slack mesmo, sem subdominio, sem redirecionamento.
Garante que nunca dará problema.

**Comment by flavianohonorato** [comment]
Show, obrigado pelo feedback.

**Comment by erikfig** [comment]
poutz... n é redirect é pra pedir convite, preciso achar isso e subir outro no lugar!!!

**Comment by flavianohonorato** [comment]
Vixi
