### ISSUE TITLE
Conditions em todas as requisições

### ISSUE THREAD

**Issue by anderson631** [CakePHPBrasil/blog#5]
Galera, criei um campo chamado "deletado" em todas as tabelas do meu BD. Quando null, aquele registro não foi excluído e quando possuir um valor, é pq foi excluído naquela data.

Preciso então inserir um 'conditions' (deletado IS NULL) nas requisições dos dados do site, para que nenhum dado retornado já tenha sido excluído.

Mas não acho viável inserir esse condition em todas as requisições, em todos os Controllers. Vcs sabem uma forma de inserir um conditions pra todas as requisições, no AppModel?

**Comment by erikfig** [comment]
Então...

O ideal é vc usar o beforeFind, e fica ainda mais legal se colocar em um Behavior, assim você só informa o behavior no Table e pronto.. ta configurado.

[Documentação sobre beforeFind](http://book.cakephp.org/3.0/en/orm/table-objects.html#beforefind)
[Um plugin para exemplo (behavior)](https://github.com/UseMuffin/Trash/blob/master/src/Model/Behavior/TrashBehavior.php)

Posta o resultado pra gente aqui depois.

Espero ter ajudado...

**Comment by tgbaldo** [comment]
Estou implementando essa técnica num sistema Multi Tenancy para trazer os registros apenasde um tenant. Não fiz via Behavior, mas no AppModel tenho um método que dá um DESC da tabela pra ver se existe um campo "tenant_id", e se existir então ele inclui um WHERE na condition para trazer os registros apenas do Tenant logado na sessão.

**Comment by tgbaldo** [comment]
Mas acho que via Behavior é melhor, pois não irá rodar o DESC em todas as model, ou seja, é uma Query a menos.

**Comment by tgbaldo** [comment]
Mas ja vi algo do tipo: $this->Model->find ('no_deleted'); mas precisa mexer no método find da classe Model pra adicionar esse parâmetro. Acho que é bom desse jeito também.

**Comment by tgbaldo** [comment]
É disse que estou falando: http://blog.thiagobelem.net/criando-um-novo-tipo-de-find-no-cakephp-2-0

Já comentei demais :)

**Comment by erikfig** [comment]
kkk...

Mas acho que é por ai.. porque se vc adicionar o soft delete, vai ter que configurar alguma coisa para trazer estes recursos "deletados" caso queira fazer uma "lixeira...

**Comment by alexsmonte** [comment]
@anderson631  usa esse plugin https://packagist.org/packages/pgbi/cakephp3-soft-delete
