### ISSUE TITLE
Replicação de dados

### ISSUE THREAD

**Issue by tgbaldo** [CakePHPBrasil/blog#6]
Pessoal,

Qual a melhor forma de replicar os dados entre dois sistemas diferentes?

Exemplo de um cenário:

Tenho uma loja virtual e um sistema ERP. Preciso que as vendas realizadas na loja virtual sejam replicadas para o ERP, e automaticamente alimentar as contas a receber do ERP.

Como posso fazer isso?

PS: a loja virtual pode ser em Wordpress, Magento, PHP puro, etc. O ERP é em CakePHP.

Abs!

**Comment by alexsmonte** [comment]
Vc deve usar recursos do banco de dados entretanto vc deve avaliar se vai fazer uni direcional  ou multi direcional.... 
Eh um negócio mto perigoso por tanto se alguém aparecer aki cm uma solução com qualquer coisa q nao seja usando recursos do banco nao use...  

Pq envolve mta coisa uma delas concorrência de dados

**Comment by lucassmacedo** [comment]
A melhor forma, ao meu ver, seria voce cria uma API, definindo regras de entrada para diferentes tipos de sistemas, seja wordpress, magento, PHP etc. Ou até mesmo criar plugins/modulos para esses CMS que sigam os padrões da API para alimentar a mesma.
Dessa forma o ERP sempre vai ser alimentado com os dados de forma correta, mesmo que a entraa seja Wordpress, Magento ou wharever.

**Comment by lucassmacedo** [comment]
A melhor forma, ao meu ver, seria voce cria uma API, definindo regras de entrada para diferentes tipos de sistemas, seja wordpress, magento, PHP etc. Ou até mesmo criar plugins/modulos para esses CMS que sigam os padrões da API para alimentar a mesma.
Dessa forma o ERP sempre vai ser alimentado com os dados de forma correta, mesmo que a entrada 
seja Wordpress, Magento ou wharever.

**Comment by erikfig** [comment]
Poutz... existem muitas formas de fazer isso, porém eu faria assim:

1. Criar uma api no CakePHP e no cliente (app que vai consumir o rest) um módulo/componente/pacote/whatever para consultar estes dados e persistir localmente, você pode implementar uma auth por token e tudo mais (OAuth2 S2).

2. Criar um cron para rodar no cliente (app que vai consumir o rest) para verificar atualizações de tempo em tempo) ou então um websocket para emitir um aviso que ouve alteração, assim você não precisa ficar rodando crons e até em consultas bidirecionais não haveria problema de conflito dos dados, já que as atualizações são real-time

p.s.:websocket no php da um trabalho dos infernos....

**Comment by alexsmonte** [comment]
@tgbaldo so nao faça pelo banco se nao puder... eh a solucao mais segura... como vc acaha q bancos como ITAU Bradesco enfim fazem esse lance ??? replicacao de dados...e tenha certeza nao eh com api nem nada eh com recuso do banco...

**Comment by alexsmonte** [comment]
http://www.devmedia.com.br/mysql-replicacao-de-dados/22923 MYSQL
http://www.devmedia.com.br/introducao-a-replicacao-e-alta-disponibilidade-no-postgresql/6140 PG

Ja fiz isso com Oracle e Mysql e funciona mto bem...

**Comment by josuecamelo** [comment]
Amigo já pensou em usar ferramentas de etl como talend open studio?

**Comment by alexsmonte** [comment]
@josuecamelo  esse talend nao eh para integracao/migracao com banco de dados?

o lance de fazer isso no banco eh q isso a grosso modo vira um "serviço" dentro do banco de dados...

**Comment by erikfig** [comment]
@alexsmonte esta solução n é a melhor... ele pode ter bases muito diferentes uma da outra e inviabiliza ele "replicar" os bancos no próprio sentido da palavra.. ele precisa na verdade integrar os aplicativos...

**Comment by tgbaldo** [comment]
A princípio tinha pensado que API resolveria o problema mesmo, mas vou estudar essa opção de fazer com banco de dados.

Mas, no caso da replicação com o banco de dados, e se eu tiver bancos de dados diferentes dois dois lados, tipo MySQL no ERP e Postgres na Loja Virtual? Pois, a ideia é tornar isso transparente.

O ERP não precisa saber qual SGBD a Loja Virtual usa. Pois, a ideia é que os clientes que já possuam lojas virtuais prontas e rodando bonitinho, fazendo as suas vendas e tal, integrem de forma descomplicada ao ERP.

Nesse caso, Alex, não seria a API uma melhor solução?

**Comment by andersonluciano** [comment]
Olá @tgbaldo trabalho em uma empresa que lida todos os dias com diversas integração entre clientes, principalmente no que se diz respeito a pedidos e faturamentos, então creio que minha opinião possa te ajudar de alguma forma.

Em tempos antigos se utilizava muito replicação de bancos igual ao que o amigo @alexsmonte esta sugerindo, só que devido a diversas questões (dificuldade de replicar bancos por conta de hospedagens, ou até por questões de segurança) hoje a replicação é mais utilizada no âmbito de infraestrutura do que no âmbito de replicação de dados entre aplicações.

Temos diversas opções de integrar, mas a mais viavel e mais utilizada hoje em dia são os webservices, seja ele em REST, ou um SOAP da vida. O @lucassmacedo ja cantou a bola ali em cima :) .

Em um webservice você consegue definir quais dados vc quer transitar entre aplicações, definir regras para ditar em que momento do processo esses dados devem ser migrados, além de não ter o trabalho de configurar uma replicação de banco, que por mais "simples" que pareça, pode trazer algumas complicações posteriores.

Tem diversos tutoriais ensinando como criar API's REST em Cake.. 

Eu hoje trabalho com integrações aqui na organização, ja fiz integrações de todos tipos.. desde arquivos postados em FTP, webservices SOAP, e as API's REST, que são mais usadas hoje em dia. Só esses tipos de integrações vai trazer para a sua aplicação um nivel de integração que vai permitir que ela venha a crescer e integrar com outros serviços futuramente.

Então fica ai minha dica, faça uma integração (REST se possivel) e com certeza o trabalho será recompensado :)

**Comment by alexsmonte** [comment]
@tgbaldo  entao o termo nao eh replicar :D pq replicacao no banco de dados remete a ideia de estamos no mesmo ambiente :D com tabelas iguais enfim

Agora se vc quer somente transportar dados entre bases diferentes ai realmente so uma API.

por dentro utilize triggers e Procedures nao faça SQL normal...  vc tem q ter o maximo de controle de transacao...

eu mesmo tenho um sistema na web q conversa com sistema em delphi utilizando uma api...

**Comment by alexsmonte** [comment]
@tgbaldo http://www.bravo-kernel.com/2015/04/how-to-build-a-cakephp-3-rest-api-in-minutes/

**Comment by wilcorrea** [comment]
Replicação != Integracação. Se o catalisador é o ERP basta os agentes enviarem os dados para ele. Se for preciso ter uma integração contínua é preciso gerar um identificador de um para o outro e planejar como pode haver uma resposta para a o agente ; )

**Comment by tgbaldo** [comment]
Vocês são fera, muito rápido a iteração, show de bola!

Então, o caminho é API RESTfull mesmo.

Acho que na modelagem do banco do ERP eu preciso criar um campo que irá armazenar a primary_key do registro da loja virtual, para saber de qual produto se trata quando uma iteração for realizada. É por ai mesmo?

**Comment by tgbaldo** [comment]
@wilcorrea, é isso mesmo que falei acima, pensamos na mesma coisa rsrs

**Comment by wilcorrea** [comment]
@tgbaldo eu iria além. Se você vai ter múltiplos agentes vai precisar ter uma forma de identificar o agente para que possa chegar com os dados de volta para ele. Além disso se múltiplos agentes estiverem usando sua base como saber quem enviou o que? Talvez um GUID ou UUID evite essa duplicidade ou seja mais eficiente ter um identificador como {prefix}-{key} onde possa chegar em quem é o agente que publicou aquele dado.

**Comment by alexsmonte** [comment]
@tgbaldo  essa questao q o @wilcorrea  falou  eh isso mesmo... 

eu tenho um sistema de vendas PDV 

e no meu caso eu gero um "UID" onde esse campo corresponde vamos supor a numero da venda onde é formatado numero do estabelcimento-PDV da venda-codigo da venda

ex: 234-654-12345678

com isso eu consigo ter o mesmo codigo em dois lugares  

evidente q tem metodos mais simples... mas para mim isso tinha q ser assim :D

**Comment by tgbaldo** [comment]
Então, o ERP é Multi Tenancy, então esse UID seria, aqui no meu caso, o "account_id", porém, iria incrementar um token para cada cliente baseado no account_id.

Na hora da iteração eu pegaria o token, verificaria de qual Account ele pertence e então pegaria o account_id e popularia o campo. O que acham?

**Comment by alexsmonte** [comment]
@tgbaldo eu nao usuaria um campo chave... mas pensando no meu...

vc vai transportar seu account_id (EXTERNO) para ser account_id(NA BASE MASTER) ??

**Comment by wilcorrea** [comment]
@tgbaldo creio que se é multi tenancy você vai precisar desse mecanismo sim, mas e o agente? Você vai tratar cada agente como um tenancy?

**Comment by tgbaldo** [comment]
Exatamente @wilcorrea. No ERP eu identifico os tenants através do campo "account_id". Então, como cada loja virtual pertence a um tenant no ERP, então preciso tratar as lojas virtuais como um agente do tenant.

**Comment by tgbaldo** [comment]
Isso mesmo @alexsmonte, mas na base da loja virtual não irá ter o campo account_id, esse campo terá apenas no ERP. Na loja virtual, precisará ser configurado um token para consumir a API do ERP, e então, quando a requisição chegar no ERP, eu identifico de qual tenant pertence aquele token, e assim definio na query (para alimentar as vendas, contas a receber, etc) o id do tenant (que é o campo "account_id").

Esse é o caminho que eu pensei por hora...

**Comment by alexsmonte** [comment]
#FECHÔ

**Comment by tgbaldo** [comment]
@erikfig, sobre OAuth (nunca vi, nem comi, só ouço falar kkkk), mas preciso estuda-lo. Mas, eu não poderia simplesmente requerer em toda requisição um token como parâmetro, e já não estaria legal? :)

**Comment by erikfig** [comment]
Até estaria @tgbaldo porém... a ideia de oauth2 é:

 * Você tem um token que dura um determinado tempo, então outro é gerado, isso garante que você não terá acessos indesejados caso o token seja descoberto, já que ele não dura muito.
 * Você autentica a aplicação antes do usuário (sim, usuário e senha, as vezes conhecidos como client e client_secret).

Este é o mesmo padrão utilizado pelo Facebook, GitHub e outros serviços que fornecem uma api.

**Comment by erikfig** [comment]
Vou fechar a issue, se precisar de mais informações sobre oauth acho bacana abrir outra para organizarmos as informações...
