### ISSUE TITLE
Redicionamento URL com htaccess no CakePHP 2.8

### ISSUE THREAD

**Issue by tgbaldo** [CakePHPBrasil/blog#7]
Pessoal, estou numa missão aqui para redirecionar e manter uma URL.

Vou usar dados fictícios, mas o cenário é real.

Tem um site rodando em www.site.com.br (é uma loja virtual). E um outro sistema dividido em duas pastas: pasta1 e pasta2, onde os usuários acessam via: www.site.com.br/pasta1 ou /pasta2.

Criei um sistema para substituir esse antigo dividido nessas pastas. Porém, o sistema está em Cake e numa pasta só: www.site.com.br/novo_sistema.

O cliente quer manter as URLs. Já tentei via iframe (deu quase certo, mas é um trampo para manter e não ficou 100%). Tentei via DNS, não consegui. E agora estou tentando via .htacess.

O que eu preciso? Simplesmente que quando o usuário digite: www.site.com.br/pasta1 ele redirecione para uma rota do Cake que já funciona em: www.site.com.br/novo_sistema/pasta1, só que sem esse "novo_sistema", e assim também para www.site.com.br/pasta2...

Levando em consideração que o Cake já tem um .htaccess no webroot, o que eu faço para conseguir essa façanha, para não ter que, simplesmente dizer ao cliente: não dá!?

### PS: na verdade vou ter que mexer no .htacess do site e não do Cake.

**Comment by erikfig** [comment]
Este é o arquivo atualizado (no momento que posto aqui) do .htaccess que vem na raiz do CakePHP 2:

```
<IfModule mod_rewrite.c>
	RewriteEngine on
	# Uncomment if you have a .well-known directory in the root folder, e.g. for the Let's Encrypt challenge
	# https://tools.ietf.org/html/rfc5785
	#RewriteRule ^(\.well-known/.*)$ $1 [L]
	RewriteRule ^$ app/webroot/ [L]
	RewriteRule (.*) app/webroot/$1 [L]
</IfModule>
```

Ali nas linhas aonde tem `RewriteRule ^$ app/webroot/ [L]` e `RewriteRule (.*) app/webroot/$1 [L]`, pode ser um tiro no escuro, já que eu mesmo não testei, porém acredito que se você:

1. Copiar (COPIAR!!!) para a raiz do projeto
2. Alterar de `app/webroot/` para `novo_sistema/app/webroot/`

Você pode já ter algum htaccess com regras que precisem ser  mantidas e vai precisar adaptar mais ainda o exemplo ao seu caso, mas ai é outra história.

Como disse, eu não testei e esse lance de htaccess é tão volúvel dependendo do servidor que eu até sai dessa joça para o nginx, então, tem que testar...

**Comment by arojunior** [comment]
Se você reparar no .htaccess da pasta raiz do Cake (para quem usa o Cake como aplicação principal), vai ver que tem as linhas:
   RewriteRule    ^$ app/webroot/    [L]
   RewriteRule    (.*) app/webroot/$1 [L]

Isso quer dizer que tudo que chega em www.site.com.br/ vai para a pasta app/webroot
Dentro das pasta app e webroot tem também os arquivos .htaccess dizendo a mesma coisa, eles também redirecionam para este nível.

Com base nisso, você pode  adicionar no seu .htaccess da sua pasta raiz as regras para /novo_sistema/pasta1 e /pasta2 antes das linhas do cake/sua aplicação.

Caso não tenha entendido bem, cole aqui o seu .htaccess e eu monto a configuração exatamente como deve ficar.

**Comment by tgbaldo** [comment]
@arojunior , o cliente ainda não me passou o .htaccess do site dele, vai me passar o acesso na hora de subir pra produção (infelizmente)... mas, creio que será o caso de apenas adicionar mais regras no htacces, não?

Fiz um teste com um htacess limpo, sem nenhuma regra antes realizada, e numa rota deu certo (vou abrir aqui pra vocês):

<IfModule mod_rewrite.c>
	RewriteEngine on
	RewriteRule ^buscarprofissionais/?$ /app_cftv_clube/buscarprofissionais [NC,L]
	RewriteRule ^cidades/?$ /app_cftv_clube/cidades [NC,L]
</IfModule>

A regra do "buscarprofissionais" deu certo. Ele está chegando numa rota definida lá no Cake, porém, a regra de "cidades" não dá certo, retorna 404. 

PS: isso aqui é uma rota do Cake: /app_cftv_clube/buscarprofissionais
PS 2: isso aqui é um controller do Cake: /app_cftv_clube/cidades

Só se eu criar uma rota pra esse controller também...

**Comment by arojunior** [comment]
@tgbaldo veja se assim resolve:

```
RewriteRule ^buscarprofissionais.*$ http://example.com/app_cftv_clube/buscarprofissionais/ [R=301,L]
RewriteRule ^cidades.*$ http://example.com/app_cftv_clube/cidades/ [R=301,L]
```

Fonte: https://mediatemple.net/community/products/dv/204643270/using-htaccess-rewrite-rules

**Comment by tgbaldo** [comment]
Estou conseguindo fazer funcionar dessa forma:

<IfModule mod_rewrite.c>
	RewriteEngine on
	RewriteRule ^buscarprofissionais/?$ /app_cftv_clube/bsucarprofissionais [NC,L]
	RewriteRule ^buscarprofissionais/cidades/index/?$ /app_cftv_clube/bsucarprofissionais/cidades/index [NC,L]
	RewriteRule ^buscarprofissionais/cidades/index_slug/?$ /app_cftv_clube/bsucarprofissionais/cidades/index [NC,L]

	RewriteRule ^instaladores/?$ /app_cftv_clube/instaladores [NC,L]
	RewriteRule ^instaladores/painel/?$ /app_cftv_clube/instaladores [NC,L]
	RewriteRule ^instaladores/painel/orcamentos/?$ /app_cftv_clube/instaladores [NC,L]
	RewriteRule ^instaladores/painel/perfil/?$ /app_cftv_clube/instaladores [NC,L]
	RewriteRule ^instaladores/painel/logout/?$ /app_cftv_clube/instaladores [NC,L]
	RewriteRule ^instaladores/painel/gold/?$ /app_cftv_clube/instaladores [NC,L]
</IfModule>

**Comment by tgbaldo** [comment]
Pessoal, acho que consegui o caminho para resolver, conforme descrevi acima. Obrigado a todos! ;)
