### ISSUE TITLE
Personalizar elemento option FormHelper - CakePHP 3

### ISSUE THREAD

**Issue by tgbaldo** [CakePHPBrasil/blog#8]
Fala pessoal, vamos gerar mais um pouco de conteúdo rsrs

Estou usando o Material Design em um projeto em CakePHP3. Estou com uma missãozinha para fazer funcionar do jeito certo o primeiro elemento 'option' da tag 'select'.

O resultado deve sair assim:

```
<select>
       <option value="" disabled selected>Selecione</option>
       <option value="1">Plano 1</option>
      <option value="2">Plano 2</option>
      <option value="3">Plano 3</option>
 </select> 
```

Porém, dando uma olhada na documentação do Cake, o máximo que eu consegui foi usar o 'empty' => 'Selecione'. Porém, não consigo setar os atributos 'disabled' e 'selected' no empty. Ele precisa vir primeiro, como de padrão o é, mas com esses atributos .

Alguma luz ?

**Comment by erikfig** [comment]
hum... veja se ajuda:

http://stackoverflow.com/questions/4099256/add-disabled-and-selected-option-to-select-item-with-form-helper

**Comment by tgbaldo** [comment]
Opa @erikfig , vou testar aqui e te falo... valeu meu nobre!
