### ISSUE TITLE
Base de Endereços: Webservice Correios vs Tabela Banco de Dados

### ISSUE THREAD

**Issue by tgbaldo** [CakePHPBrasil/blog#9]
Fala pessoal, tudo bem?

Atualmente eu utilizo o REST da ViaCep para buscar informações de endereços com base no CEP (https://viacep.com.br/), e ainda mantenho uma base de dados todos os estados e cidades do Brasil, e faço o relacionamento com o cadastro (clientes, fornecedores, etc).

Porém, surgiu uma necessidade de ter endereços de outros países. Não acho viável tentar manter uma base de dados de todos as cidades e estados de todos os países do mundo, como iria manter isso atualizado?

Então, eu fiz uma integração com o Gmaps, onde eu pego as coordenadas do local, a cidade, o estado, o país, e até mesmo o place_id. Porém, já ouvi gente falar que o Google não atualiza isso constantemente.

Qual, na opinião de vocês seria a melhor solução?

Abs!

**Comment by erikfig** [comment]
Hum... na verdade cara... eu ACHO que vai ser difícil achar estes dados atualizados, é muita mão de obra pra manter, então acho que este caminho é o melhor possível...

Obviamente alguém pode ter uma sugestão melhor.... fiquem a vontade

**Comment by tgbaldo** [comment]
Legal Erik, vou manter o gmaps mesmo. Mas, aceito mais sugestões do pessoal...
